### ISSUE TITLE
main_background.jpg is missing

### ISSUE THREAD

**Issue by sschip** [krinskils/chess#2]
(my_env) C:\Projects\python\pygame\BeCheZ>python main.py
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 178, in <module>
    main()
  File "main.py", line 160, in main
    screen.add_squares_to_board()
  File "C:\Projects\python\pygame\BeCheZ\screen.py", line 71, in add_squares_to_board
    bg_image = pygame.image.load(os.path.join(PICTURES_PATH, 'main_background.jpg'))
FileNotFoundError: No such file or directory.

**Comment by guykrinsky** [comment]
Fixed
